# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_chapter',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(verbose_name='书目id')),
                ('name', models.CharField(max_length=30, verbose_name='章节名')),
                ('chapter', models.IntegerField(verbose_name='章节数')),
            ],
            options={
                'verbose_name': '书名',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.AddField(
            model_name='book_name',
            name='chapter_total',
            field=models.IntegerField(default=10, verbose_name='章节总数'),
            preserve_default=False,
        ),
    ]
