# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20180130_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_name',
            name='brief',
            field=models.TextField(default=22, max_length=140, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
