# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_book_name_brief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_chapter',
            old_name='chapter',
            new_name='chapter_number',
        ),
    ]
