# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20180130_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tags',
            name='chapter_id',
            field=models.IntegerField(default=1, verbose_name='章节id'),
            preserve_default=False,
        ),
    ]
