# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20180201_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_chapter',
            name='chapter_number',
            field=models.IntegerField(verbose_name='章节id'),
        ),
    ]
