# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20180201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_tags',
            name='name',
            field=models.CharField(default=0, max_length=30, verbose_name='章节名'),
            preserve_default=False,
        ),
    ]
