# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('coursetype', models.CharField(max_length=30)),
                ('brief', models.TextField()),
                ('years', models.IntegerField()),
                ('starttime', models.CharField(max_length=30)),
                ('endtime', models.CharField(max_length=30)),
                ('enrolment', models.IntegerField()),
                ('imgurl', models.CharField(max_length=30)),
                ('fileurl', models.CharField(max_length=30)),
                ('teacher', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('goodat', models.TextField()),
                ('evaluation', models.TextField()),
                ('courseroffer', models.IntegerField()),
                ('days', models.IntegerField()),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=30)),
                ('evaluator', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='histroy',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('companyname', models.CharField(max_length=30)),
                ('couseid', models.CharField(max_length=30)),
                ('teacherid', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('imgurl', models.CharField(max_length=30)),
                ('imgurll', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('courseid', models.IntegerField()),
            ],
        ),
    ]
