# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(max_length=36, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('count', models.IntegerField(max_length=30)),
            ],
        ),
    ]
