# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histroy',
            name='imgurl',
            field=models.CharField(max_length=300),
        ),
    ]
