# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20171205_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='histroy',
            new_name='history',
        ),
    ]
