# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20171128_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('coursetype', models.CharField(max_length=30)),
                ('brief', models.TextField()),
                ('years', models.IntegerField()),
                ('starttime', models.CharField(max_length=30)),
                ('endtime', models.CharField(max_length=30)),
                ('enrolment', models.IntegerField()),
                ('imgurl', models.CharField(max_length=30)),
                ('fileurl', models.CharField(max_length=30)),
                ('teacher', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('goodat', models.TextField()),
                ('evaluation', models.TextField()),
                ('courseroffer', models.IntegerField()),
                ('days', models.IntegerField()),
                ('province', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
