# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20171205_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='filtertype',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
