# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_history_filtertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='top',
            field=models.CharField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
