# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_history_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecturer',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('brief', models.TextField(max_length=140)),
                ('top', models.CharField(max_length=6)),
                ('couseid', models.CharField(max_length=10)),
                ('imgurl', models.CharField(max_length=300)),
                ('content', models.TextField(max_length=140)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('fileurl', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
