# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_lecturer_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='couseid',
            new_name='courseid',
        ),
    ]
