# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0008_auto_20171206_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('companyname', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=30)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
