# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '课程库'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '客户反馈'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '往期回顾'},
        ),
        migrations.AlterModelOptions(
            name='lecturer',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '讲师信息'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '客户留言'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': '选课报名', 'verbose_name_plural': '报名信息'},
        ),
        migrations.AlterField(
            model_name='message',
            name='companyname',
            field=models.TextField(max_length=30, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.TextField(max_length=30, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=300, verbose_name='留言'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(verbose_name='电话'),
        ),
    ]
